players:
  list:
    - tag: Q92CC2UG
      name: うめぼっし
      twitter: 
    - tag: 2RC89GJ
      name: iAmJP
      twitter: iAmJPey
    - tag: 2RLCCGYL
      name: Michifu☆
      twitter: michifucr
    - tag: PPV2JUUGU
      name: Twitch/Boss_CR
      twitter: Boss_CR_
    - tag: QVPJRV
      name: SaintBelikin
      twitter: SaintBelikin
    - tag: LPRR9P
      name: RUBÉN
      twitter: rubizalez
    - tag: 98GPG9
      name: Karnage
      twitter: KarnageZpain
    - tag: 2YVRY8YU
      name: Wings
      twitter: wings
    - tag: GYUQQCLV
      name: Anaban
      twitter: Anaban_Cr
    - tag: Y2LP0CU
      name: IMT LaPoKaTi
      twitter: LaPoKaTi
    - tag: C8PU2RYY
      name: Surg TS
      twitter: Surg_Ts
    - tag: 2YJRUQ2Q
      name: Oxalate
      twitter: Oxalate_Gaming
    - tag: JQJGRJ
      name: TQ Cuchii Cuu
      twitter: Cuchii_Cu
    - tag: 2YGQVGQ9
      name: DiegoB
      twitter: DiegoB_CR
    - tag: 2R8P28
      name: Pompeyo4
      twitter: Pompeyo4CR
    - tag: YRVL9U98
      name: JACK
      twitter: JACK15842169
    - tag: 8GLUYL
      name: VULKan
      twitter: IsaacGrindinger
    - tag: P00G928VC
      name: YersonCz
      twitter: CzYerson
    - tag: P2U9G2J
      name: sergioramos
      twitter: SergioRamosCR
    - tag: 22Y9CGYGQ
      name: Dark Light
      twitter: DarkLightCR
    - tag: L2JGQQ8L
      name: Regue
      twitter: Regue_CR
    - tag: YYYQ0VR2
      name: ah craaaap
      twitter: ahcraaaap
    - tag: PP0VL8LC
      name: TQ BENIJU
      twitter: BENIJU03
    - tag: CLQP9R9
      name: Bale
      twitter: Real_BaleGame
    - tag: PC2UCJ2Y
      name: Ivan Abuso
      twitter: IvanManyu
    - tag: R09228V
      name: SK Morten
      twitter: mortenroyale
    - tag: 2LQ2YP98
      name: xopxsam
      twitter: xopxsam_
    - tag: GVGGGPJP
      name: Hajime
      twitter: Hajime_CR_
    - tag: 9YVGC8
      name: Tobi SpiritHawk
      twitter: Tobi_SpiritHawk
    - tag: 228RR0GR
      name: thegod_rf
      twitter: thegod_rf
    - tag: PLQ89QRRU
      name: SamyBDZ
      twitter: SamyBdz
    - tag: YJLJ98U
      name: DIG Blaze
      twitter: BlazeCR_
    - tag: Y2C0RLR
      name: X-Bow Master
      twitter: XbowMaster_
    - tag: 9PJ8U8RY
      name: Boeufmac
      twitter: Boeufmac
    - tag: VLURPP9
      name: xPedro15
      twitter: xPedro15
    - tag: LPL2UQVJ
      name: Azilys☆
      twitter: Azilysgames
    - tag: VYCCJ8Q
      name: Ferchu
      twitter: G2Ferchu_13
    - tag: 8VCGGL
      name: TQ CM AWESOME
      twitter: AbusivoCm
    - tag: 88JY0VGU
      name: Unstoppable
      twitter: Unstoppable_CR
    - tag: 8YGJVUCP
      name: ThatOneGuy
      twitter: ThatoneguyCr
    - tag: R9QJRCY
      name: Berin
      twitter: Berin
    - tag: GLJC0G
      name: KIX™️ Legend
      twitter: LegendCr266
    - tag: 9V82GGCQ
      name: King Joao
      twitter: KingJoaoCr
    - tag: 88QUJ0J8
      name: ShiR☆
      twitter: G2ShiR
    - tag: RPRPCGU
      name: Mikel04
      twitter: Mikeel04
    - tag: PGQ9G29P
      name: Coltonw83
      twitter: colton_wall
    - tag: 99CYUP9
      name: Super Loupanji
      twitter: loupanji
    - tag: Anthony
      name: 209U29L2P
      twitter: AnthonyD_Angelo
    - tag: 2JC0JRL2
      name: Adrian Piedra
      twitter: adrianpiedracr
    - tag: 8U0QCJ2
      name: B-rad
      twitter: B_radCR
    - tag: 92L9R2JG
      name: Surgical Goblin
      twitter: SurgicalGoblin
    - tag: 220L9GC2
      name: KaNaRiOoo
      twitter: KaNaRiOoo
    - tag: 9VGL08QJ
      name: zTeemper
      twitter: zTeempeer
    - tag: QC0GUGJ0
      name: Soking
      twitter: SokingRcQ
    - tag: Y9V2UL9C
      name: SK sergioramos
      twitter: SergioRamosCR
    - tag: YJC0Q2CP
      name: Mthja
      twitter: mthjaCR
    - tag: 282LVUP
      name: MusicMaster
      twitter: MusicMasterCR
      